// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtUPBtLotAkMMlVPg3dPrF2XHGAdjWqY',
    appId: '1:38214154268:android:389d0b2305d64c9c5007d9',
    messagingSenderId: '38214154268',
    projectId: 'squadup-693f4',
    storageBucket: 'squadup-693f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE0_eaB-PKeNnyjUwOzYxXMPtnCd6F-nU',
    appId: '1:38214154268:ios:ba8f2035f43f30555007d9',
    messagingSenderId: '38214154268',
    projectId: 'squadup-693f4',
    storageBucket: 'squadup-693f4.firebasestorage.app',
    iosBundleId: 'com.squadup.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfCVUaSTm3o-htWXePfpBHPEM-Xqg1Qv4',
    appId: '1:38214154268:web:0c12b563561995945007d9',
    messagingSenderId: '38214154268',
    projectId: 'squadup-693f4',
    authDomain: 'squadup-693f4.firebaseapp.com',
    storageBucket: 'squadup-693f4.firebasestorage.app',
    measurementId: 'G-43BQB53WJH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE0_eaB-PKeNnyjUwOzYxXMPtnCd6F-nU',
    appId: '1:38214154268:ios:90c0a9e561aaa7aa5007d9',
    messagingSenderId: '38214154268',
    projectId: 'squadup-693f4',
    storageBucket: 'squadup-693f4.firebasestorage.app',
    iosBundleId: 'com.example.squadupv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfCVUaSTm3o-htWXePfpBHPEM-Xqg1Qv4',
    appId: '1:38214154268:web:30ef0de48e5b71935007d9',
    messagingSenderId: '38214154268',
    projectId: 'squadup-693f4',
    authDomain: 'squadup-693f4.firebaseapp.com',
    storageBucket: 'squadup-693f4.firebasestorage.app',
    measurementId: 'G-7RSSKFY7B0',
  );

}