-- Disable RLS for development
-- WARNING: This should only be used in development environments
-- Re-enable RLS before deploying to production

-- Disable RLS on all tables
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE squads DISABLE ROW LEVEL SECURITY;
ALTER TABLE squad_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE squad_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE message_reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE message_read_receipts DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_details DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_raw_archive DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_checkins DISABLE ROW LEVEL SECURITY;
ALTER TABLE races DISABLE ROW LEVEL SECURITY;
ALTER TABLE race_squads DISABLE ROW LEVEL SECURITY;

-- Note: To re-enable RLS in production, run:
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE squads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE squad_members ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE activity_summaries ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE activity_details ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE expert_responses ENABLE ROW LEVEL SECURITY;
